# caller example
#jobs:
#  call-workflow-gitleaks-scan:
#    uses: button-inc/button-shared-gh-actions/.github/workflows/scan-code-gitleaks.yml@develop
#    with:
#      notify-user-list: "@shon-button,@YaokunLin"
#    secrets:
#      github-token: ${{ secrets.GITHUB_TOKEN }}
#      gitleaks-license: ${{ secrets.GITLEAKS_LICENSE}}

name: Gitleaks Scan Code

on:
  workflow_call:
    inputs:
      notify-user-list: 
        required: false
        type: string
    secrets:
      github-token: 
        required: true
      gitleaks-license: 
        required: true

concurrency:
  group: callee-gitleaks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          GITLEAKS_LICENSE: ${{ secrets.gitleaks-license }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ inputs.notify-user-list }}
