# caller example
#jobs:
#  call-workflow-sonarcloud-scan:
#    uses: button-inc/button-shared-gh-actions/.github/workflows/scan-code-sonarcloud.yml@develop
#    secrets:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}

name: Sonarcloud Scan Code

on:
  workflow_call:
    inputs:
      configs-placeholder: 
        required: false
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

concurrency:
  group: callee-sonarcloud-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarcloud: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
